// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv43W__d561vMfQgxeBEKbzCSHrE6b3vU',
    appId: '1:138772656427:web:b51aeb319960155507156e',
    messagingSenderId: '138772656427',
    projectId: 'eduflexapp-69747',
    authDomain: 'eduflexapp-69747.firebaseapp.com',
    storageBucket: 'eduflexapp-69747.appspot.com',
    measurementId: 'G-XG77RKETN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1RtSYIR-n9Klmld-xFBk7yTw18rwBxo',
    appId: '1:138772656427:android:406692091ed651c607156e',
    messagingSenderId: '138772656427',
    projectId: 'eduflexapp-69747',
    storageBucket: 'eduflexapp-69747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcE6znbAujZ8KUMq-ndeQzKyzCbbFO1lY',
    appId: '1:138772656427:ios:cf25390c993f18bb07156e',
    messagingSenderId: '138772656427',
    projectId: 'eduflexapp-69747',
    storageBucket: 'eduflexapp-69747.appspot.com',
    iosBundleId: 'com.example.eduflex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcE6znbAujZ8KUMq-ndeQzKyzCbbFO1lY',
    appId: '1:138772656427:ios:a8c4a3de68f816de07156e',
    messagingSenderId: '138772656427',
    projectId: 'eduflexapp-69747',
    storageBucket: 'eduflexapp-69747.appspot.com',
    iosBundleId: 'com.example.eduflex.RunnerTests',
  );
}
